builds:
  - binary: janet
    main: ./cmd/janet/main.go
    ldflags: -s -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
  - binary: janetctl
    main: ./cmd/janetctl/main.go
    ldflags: -s -extldflags "-static"
    goos:
      - linux
    goarch:
      - amd64
snapshot:
  name_template: "{{ .Tag }}-next"
git:
  short_hash: true
dockers:
  - image: troyxmccall/janet
    binary: janet
    dockerfile: ./cmd/janet/Dockerfile-goreleaser
    tag_templates:
      - "{{ .Version }}"
      - latest
  - image: troyxmccall/janet
    binary: janet
    dockerfile: ./cmd/janet/Dockerfile-webui-goreleaser
    tag_templates:
      - "{{ .Version }}-webui"
      - latest-webui
    extra_files:
      - www
  - image: troyxmccall/janetctl
    binary: janetctl
    dockerfile: ./cmd/janetctl/Dockerfile-goreleaser
    tag_templates:
      - "{{ .Version }}"
      - latest
